version = 1

test_patterns = [
  "tests/**"
]

exclude_patterns = [
  "vendor/**"
]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "php"

[analyzers.meta]
  bootstrap_files = ["vendor/autoload.php"]
  skip_doc_coverage = ["class", "magic", "nonpublic"]

[[transformers]]
name = "php-cs-fixer"